config/routes.rb
Rails.application.routes.draw do
  resources :patients do
    collection do
      get 'copd'
      get 'asthma'
    end
  end
  resources :users, only: [:index, :new, :create, :edit, :update]

  root    'home#index'
  get     'login', to: 'sessions#new'
  post    'login', to: 'sessions#create'
  delete  'logout', to: 'sessions#destroy'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, :all if user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :birth, presence: true
  validates :mobile, presence: true
  validates :smoke, presence: true
  validates :smoke_age, presence: :is_smoker?
  validates :smoke_freq, presence: :is_smoker?
  validates :job, presence: true
  validates :address, presence: true

  scope :copd, -> { where(patient_type: 'copd') }
  scope :asthma, -> { where(patient_type: 'asthma') }

  def is_smoker?
    smoke == 1 || smoke == 3
  end

  def patient_type_o
    patient_type == 'copd' ? 'COPD' : '哮喘'
  end

  def gender_o
    gender == '1' ? '男' : '女'
  end

  def smoke_o
    smoke_items = %w(吸烟 不吸烟 已戒烟)
    result = smoke_items[smoke.to_i - 1]
    result = result + '（已吸烟' + smoke_age + '年，' + smoke_freq + '支/日' + '）' unless (patient_type == 'asthma' || smoke == 2)
    result
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  ROLES = %w[admin operator]

  def admin?
    self.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to login_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :auth_check
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:edit, :update, :destroy]
  before_action :auth_check

  def index
    pt = params[:pt]
    @pt = pt
    if pt == 'copd'
      @patients = if current_user.admin?
                    Patient.copd
                  else
                    Patient.copd.where(user_id: current_user.id)
                  end
    else
      @patients = if current_user.admin?
                    Patient.asthma
                  else
                    Patient.asthma.where(user_id: current_user.id)
                  end
    end
    respond_to do |format|
      format.html
    end
  end

  def copd
    @patients = if current_user.admin?
                  Patient.copd
                else
                  Patient.copd.where(user_id: current_user.id)
                end
    respond_to do |format|
      format.xls
    end
  end

  def asthma
    @patients = if current_user.admin?
                  Patient.asthma
                else
                  Patient.asthma.where(user_id: current_user.id)
                end
    respond_to do |format|
      format.xls
    end
  end

  def new
    pt = params[:pt]
    @patient = Patient.new
    @patient.patient_type = pt == 'copd' ? 'copd' : 'asthma'
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    respond_to do |format|
      if @patient.save
        flash.now[:success] = '患者登记成功！'
        format.html do
          if @patient.patient_type == 'copd'
            redirect_to patients_path({ pt: 'copd' })
          else
            redirect_to patients_path({ pt: 'asthma' })
          end
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    # debugger
    respond_to do |format|
      if @patient.update(patient_params)
        flash.now[:success] = '患者更新成功！'
        format.html do
          if @patient.patient_type == 'copd'
            redirect_to patients_path({ pt: 'copd' })
          else
            redirect_to patients_path({ pt: 'asthma' })
          end
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @patient.destroy
    respond_to do |format|
      format.html do
        if @patient.patient_type == 'copd'
          redirect_to patients_path({ pt: 'copd' }), notice: '患者删除成功！'
        else
          redirect_to patients_path({ pt: 'asthma' }), notice: '患者删除成功！'
        end
      end
    end
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient)
          .permit(:name, :age, :gender, :birth, :job, :smoke, :smoke_age, :smoke_freq, :email, :address, :postcode, :home_tel, :work_tel, :mobile, :patient_type, :diagnose, :note, :fev_fvc, :fev_pred, :lung_grade, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user
      user_login user
      redirect_to root_url
    else
      flash.now[:danger] = '用户名或者密码错误'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:danger] = '保存成功'
      redirect_to root_path
    else
      flash.now[:danger] = '保存失败'
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message
    message = ''
    message << (content_tag :div, flash[:success], class: 'text-success') if flash[:success]
    message << (content_tag :div, flash[:info], class: 'text-info') if flash[:info]
    message << (content_tag :div, flash[:danger], class: 'text-danger') if flash[:danger]
    sanitize message
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
  def export_path(pt)
    if pt == 'copd'
      copd_patients_path(format: 'xls')
    else
      asthma_patients_path(format: 'xls')
    end
  end
end

app/helpers/sessions_helper.rb
# 登录相关帮助方法
module SessionsHelper
  def user_login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def user_logined?
    !current_user.nil?
  end

  def auth_check
    if !user_logined?
      redirect_to login_path
    end
  end

  def login_from_session
    if session[:user_id].present?
      begin
        User.find session[:user_id]
      rescue
        session[:user_id] = nil
      end
    end
  end

  def current_user
    @current_user ||= login_from_session
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
    session.delete(:last_active_at)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_filter.html.erb
<div class="row filter">
  <div class="col-md-12">
    <label class="checkbox-inline">
      <input type="checkbox" name="patient_type" value="copd">
      COPD
    </label>
    <label class="checkbox-inline">
      <input type="checkbox" name="patient_type" value="asthma">
      哮喘
    </label>
    <%= link_to '新建患者', '#', class: "pull-right btn btn-primary" %>
  </div>
</div>

app/views/home/index.html.erb
<%= provide(:title, '请选择系统') %>
<div class="text-center">
  <h2>请选择需要登录的系统</h2>
</div>
<hr>
<div class="system-seletor">
  <ul class="list-inline">
    <li>
      <h1><span class="glyphicon glyphicon-edit text-primary"></span></h1>
      <h4>COPD患者登记系统</h4>
      <%= link_to '进入系统', patients_path({ pt: 'copd' }), class: "btn btn-primary" %>
    </li>
    <li>
      <h1><span class="glyphicon glyphicon-edit text-primary"></span></h1>
      <h4>哮喘患者登记系统</h4>
      <%= link_to '进入系统', patients_path({ pt: 'asthma' }), class: "btn btn-primary" %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <div class="navbar-brand">
            <%= image_tag 'logo.png', height: '50px' %>
            <span><%= yield :title %></span>
          </div>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_logined? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.realname %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%# link_to '修改密码', edit_user_path(current_user) %>
              </li>
              <% if current_user.admin? %>
              <li>
                <%# link_to '添加账号', new_user_path %>
              </li>
              <% end %>
              <li>
                <%= link_to '重新选择系统', root_path %>
              </li>
              <li>
                <%= link_to '退出', logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to '登录', login_path %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_filter.html.erb
<div class="row filter">
  <!-- <div class="col-md-2">
    <label class="checkbox-inline">
      <input type="checkbox" name="patient_type" value="copd">
      COPD
    </label>
    <label class="checkbox-inline">
      <input type="checkbox" name="patient_type" value="asthma">
      哮喘
    </label>
  </div>
  <div class="col-md-4 form-inline">
    <input type="text" class="form-control input-sm" placeholder="输入患者姓名进行搜索">
    <button type="button" class="btn btn-primary btn-sm">搜索</button>
  </div> -->
  <div class="col-md-12">
    <p class="pull-left">
      患者总数：<%= @patients.size %>
      人
    </p>
    <%= link_to "导出患者", export_path(@pt), class: "btn btn-primary btn-sm pull-right export" if current_user.admin? %>
    <%= link_to "新建患者", new_patient_path({ pt: @pt }), class: "btn btn-primary btn-sm pull-right" %>
  </div>
</div>

app/views/patients/_form.html.erb
<%= form_for(patient, html: { class: "form-horizontal patient-form" }) do |f| %>
<fieldset class="narrow">
  <% if patient.errors.any? %>
  <div id="error_explanation">
    <p class="text-center text-danger">提交失败表单还存在一下问题：</p>
    <ul>
      <% patient.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <p class="text-center text-muted">
      <span class="glyphicon glyphicon-info-sign"></span>
      带 * 号为必填项
    </p>
  </div>
  <%= hidden_field_tag 'patient[user_id]', current_user.id %>
  <%= hidden_field_tag 'patient[patient_type]', patient.patient_type || params[:format] %>
  <div class="form-group">
    <%= f.label :name, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control input-sm" %>
    </div>
    <%= f.label :age, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <div class="input-group">
        <%= f.text_field :age, class: "form-control input-sm" %>
        <div class="input-group-addon">岁</div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :gender, class: 'col-md-2 control-label' %>
    <div class="col-md-4">
      <div class="col-md-6 radio">
        <label>
          <input type="radio" name="patient[gender]" id="optionMale" value="1" <%= 'checked' if patient.gender == '1' %>>
          男
        </label>
      </div>
      <div class="col-md-6 radio">
        <label>
          <input type="radio" name="patient[gender]" id="optionFemale" value="2" <%= 'checked' if patient.gender == '2' %>>
          女
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birth, class: 'col-md-2 control-label' %>
    <div class="col-md-4">
      <%= f.date_field :birth, class: 'form-control input-sm' %>
    </div>
    <%= f.label :mobile, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_field :mobile, class: "form-control input-sm" %>
    </div>
    <%# f.label :age, class: "control-label col-md-2" %>
    <!-- <div class="col-md-4"> -->
    <%# (DateTime.now - patient.birth).to_i / 365 + 1 %>
    <!-- 岁 -->
    <!-- </div> -->
  </div>
  <div class="form-group">
    <%= f.label :smoke, class: "control-label col-md-2" %>
    <div class="col-md-2">
      <%= f.select :smoke, { "吸烟" => 1, "不吸烟" => 2, "已戒烟" => 3 }, class: "form-control input-sm" %>
    </div>
    <% if patient.patient_type == 'copd' %>
    <div class="col-md-4">
      <div class="input-group">
        <%= f.text_field :smoke_age, class: "form-control input-sm" %>
        <div class="input-group-addon">年</div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group">
        <%= f.text_field :smoke_freq, class: "form-control input-sm" %>
        <div class="input-group-addon">支/日</div>
      </div>
    </div>
    <% else %>
    <div class="col-md-4">
      <div class="input-group">
        <%= f.hidden_field :smoke_age, class: "form-control input-sm", value: 0 %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group">
        <%= f.hidden_field :smoke_freq, class: "form-control input-sm", value: 0 %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :job, class: "control-label col-md-2" %>
    <div class="col-md-3">
      <%= f.text_field :job, class: "form-control input-sm" %>
    </div>
    <%= f.label :email, class: "control-label col-md-2" %>
    <div class="col-md-5">
      <%= f.text_field :email, class: "form-control input-sm" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "control-label col-md-2" %>
    <div class="col-md-6">
      <%= f.text_field :address, class: "form-control input-sm" %>
    </div>
    <%= f.label :postcode, class: "control-label col-md-2" %>
    <div class="col-md-2">
      <%= f.text_field :postcode, class: "form-control input-sm" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :home_tel, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_field :home_tel, class: "form-control input-sm" %>
    </div>
    <%= f.label :work_tel, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_field :work_tel, class: "form-control input-sm" %>
    </div>
  </div>
  <% if patient.patient_type == 'copd' %>
  <div class="form-group">
    <%= f.label '支气管舒张剂后肺功能', class: "control-label col-md-2" %>
    <%= f.label :fev_fvc, class: "control-label col-md-2" %>
    <div class="col-md-3">
      <div class="input-group">
        <%= f.text_field :fev_fvc, class: "form-control input-sm" %>
        <div class="input-group-addon">%</div>
      </div>
    </div>
    <%= f.label :fev_pred, class: "control-label col-md-2" %>
    <div class="col-md-3">
      <div class="input-group">
        <%= f.text_field :fev_pred, class: "form-control input-sm" %>
        <div class="input-group-addon">%</div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lung_grade, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <div class="col-md-3 radio">
        <label>
          <input type="radio" name="patient[lung_grade]" id="option1" value="1" disabled <%= 'checked' if patient.lung_grade == '1' %>>
          1
        </label>
      </div>
      <div class="col-md-3 radio">
        <label>
          <input type="radio" name="patient[lung_grade]" id="option2" value="2" disabled <%= 'checked' if patient.lung_grade == '2' %>>
          2
        </label>
      </div>
      <div class="col-md-3 radio">
        <label>
          <input type="radio" name="patient[lung_grade]" id="option3" value="3" disabled <%= 'checked' if patient.lung_grade == '3' %>>
          3
        </label>
      </div>
      <div class="col-md-3 radio">
        <label>
          <input type="radio" name="patient[lung_grade]" id="option4" value="4" disabled <%= 'checked' if patient.lung_grade == '4' %>>
          4
        </label>
      </div>
    </div>
  </div>
<% else %>
  <div class="form-group">
    <%= f.label :diagnose, class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.select :diagnose, { "过敏性鼻炎" => 1, "慢阻肺" => 2 }, class: "form-control input-sm" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :note, class: "control-label col-md-2" %>
    <div class="col-md-10">
      <%= f.text_area :note, class: "form-control input-sm" %>
    </div>
  </div>
  <% end %>
</fieldset>
<br>
<div class="actions text-center">
  <%= f.submit '提交', class: "btn btn-primary" %>
  <%= link_to '返回', :back, class: "btn btn-default" %>
</div>
<% end %>

<script type="text/javascript">
  <% if patient.patient_type == 'copd' %>
    (function(){
      $('#patient_smoke').on('change', function(event){
        if(event.target.value === "2") {
          $('#patient_smoke_age').val('0').prop('disabled', true);
          $('#patient_smoke_freq').val('0').prop('disabled', true);
        } else {
          $('#patient_smoke_age').val('').prop('disabled', false);
          $('#patient_smoke_freq').val('').prop('disabled', false);
        }
      });

      function lung_grade_change() {
        var fev_fvc_value = parseFloat($('#patient_fev_fvc').val());
        var fev_pred_value = $('#patient_fev_pred').val();
        if (!isNaN(fev_fvc_value) && !isNaN(fev_pred_value)) {
          if (fev_fvc_value < 70) {
            if (fev_pred_value >= 80) {
              $('input[name="patient[lung_grade]"]:eq(0)').prop('checked', true);
            } else if (fev_pred_value < 80 && fev_pred_value >= 50) {
              $('input[name="patient[lung_grade]"]:eq(1)').prop('checked', true);
            } else if (fev_pred_value < 50 && fev_pred_value >= 30) {
              $('input[name="patient[lung_grade]"]:eq(2)').prop('checked', true);
            } else {
              $('input[name="patient[lung_grade]"]:eq(3)').prop('checked', true);
            }
          } else {
            $('input[name="patient[lung_grade]"]:eq(0)').prop('checked', false);
          }
        }
      }

      $('#patient_fev_fvc').on('change', lung_grade_change);
      $('#patient_fev_pred').on('change', lung_grade_change);
    })();
  <% end %>
</script>

app/views/patients/asthma.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="哮喘患者">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">序号</Data></Cell>
        <Cell><Data ss:Type="String">姓名</Data></Cell>
        <Cell><Data ss:Type="String">性别</Data></Cell>
        <Cell><Data ss:Type="String">出生日期</Data></Cell>
        <Cell><Data ss:Type="String">职业</Data></Cell>
        <Cell><Data ss:Type="String">是否吸烟</Data></Cell>
        <Cell><Data ss:Type="String">烟龄</Data></Cell>
        <Cell><Data ss:Type="String">频率</Data></Cell>
        <Cell><Data ss:Type="String">邮箱</Data></Cell>
        <Cell><Data ss:Type="String">住址</Data></Cell>
        <Cell><Data ss:Type="String">邮编</Data></Cell>
        <Cell><Data ss:Type="String">家庭电话</Data></Cell>
        <Cell><Data ss:Type="String">工作电话</Data></Cell>
        <Cell><Data ss:Type="String">手机号码</Data></Cell>
        <Cell><Data ss:Type="String">诊断</Data></Cell>
        <Cell><Data ss:Type="String">备注</Data></Cell>
      </Row>
    <% @patients.each do |patient| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= patient.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.gender_o %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.birth %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.job %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.smoke %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.smoke_age %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.smoke_freq %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.address %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.postcode %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.home_tel %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.work_tel %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.mobile %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.diagnose %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.note %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/patients/copd.html.erb
<%= provide(:title, 'COPD患者登记系统') %>
<p class="text-center text-success">
  <%= notice %>
</p>
<%= render 'patients/filter' %>
<table class="table">
  <thead>
    <tr>
      <th>序号</th>
      <th>患者类型</th>
      <th>姓名</th>
      <th>性别</th>
      <th>出生日期</th>
      <th>手机号码</th>
      <th>住址</th>
      <th>填表医生</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.id %></td>
        <td><span class="label label-info"><%= patient.patient_type_o %></span></td>
        <td><%= patient.name %></td>
        <td><%= patient.gender_o %></td>
        <td><%= patient.birth %></td>
        <td><%= patient.mobile %></td>
        <td><%= patient.address %></td>
        <td><%= User.find_by(id: patient.user_id).realname if User.find_by(id: patient.user_id) %></td>
        <!-- <td><%# link_to '查看', patient, class: "btn btn-primary btn-xs"  %></td> -->
        <td><%= link_to '编辑', edit_patient_path(patient), class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to '删除', patient, method: :delete, data: { confirm: '确定删除?' }, class: "btn btn-danger btn-xs"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/patients/edit.html.erb
<%= provide(:title, '编辑患者') %>
<h2 class="text-center"><%= @patient.patient_type == 'copd' ? ' COPD ' : '哮喘' %>患者登记信息卡</h2>
<hr>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'form', patient: @patient %>
  </div>
</div>

app/views/patients/index.html.erb
<%= provide(:title, (@patient_type == 'copd' ? 'COPD' : '哮喘') + '患者登记系统') %>
<p class="text-center text-success">
  <%= notice %>
</p>
<%= render 'patients/filter' %>
<table class="table">
  <thead>
    <tr>
      <th>序号</th>
      <th>患者类型</th>
      <th>姓名</th>
      <th>性别</th>
      <th>出生日期</th>
      <th>手机号码</th>
      <th>吸烟情况</th>
      <th>住址</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.id %></td>
        <td><span class="label label-info"><%= patient.patient_type_o %></span></td>
        <td><%= patient.name %></td>
        <td><%= patient.gender_o %></td>
        <td><%= patient.birth %></td>
        <td><%= patient.mobile %></td>
        <td><%= patient.smoke_o %></td>
        <td><%= patient.address %></td>
        <td><%= link_to '编辑', edit_patient_path(patient), class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to '删除', patient, method: :delete, data: { confirm: '确定删除?' }, class: "btn btn-danger btn-xs"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/patients/new.html.erb
<%= provide(:title, '新建患者') %>
<h2 class="text-center"><%= @patient.patient_type == 'copd' ? ' COPD ' : '哮喘' %>患者登记信息卡</h2>
<hr>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'form', patient: @patient %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, '修改密码') %>
<div class="text-center">
  <h1>修改密码</h1>
</div>
<br>
<%= form_for @user, html: { class: 'login-form' } do |f| %>
<div class="form-group">
  <%= flash_message %>
</div>
<div class="list-group">
  <div class="list-group-item">
    <%= f.password_field :origin_password, class: "form-control form-control-clear", placeholder: '请输入原密码' %>
  </div>
  <div class="list-group-item">
    <%= f.password_field :password, class: "form-control form-control-clear", placeholder: '请输入新密码' %>
  </div>
  <div class="list-group-item">
    <%= f.password_field :password_confirmation, class: "form-control form-control-clear", placeholder: '请确认新密码' %>
  </div>
</div>
<div class="form-group">
  <%= f.submit '提交', class: "btn btn-primary btn-block" %>
</div>
<div class="form-group">
  <p class="text-muted">
    <span class="glyphicon glyphicon-info-sign"></span>
    如忘记密码，请联系管理员
  </p>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, '添加用户') %>

<div class="text-center">
  <h1>添加用户</h1>
</div>
<hr>
<%= form_for @user, html: { class: 'login-form' } do |f| %>
<div class="form-group">
  <%= flash_message %>
</div>
<div class="list-group">
  <div class="list-group-item">
    <%= f.text_field :name, class: "form-control form-control-clear", placeholder: '请输入用户名' %>
  </div>
  <div class="list-group-item">
    <%= f.password_field :password, class: "form-control form-control-clear", placeholder: '请输入密码' %>
  </div>
</div>
<div class="form-group">
  <%= f.submit '保存', class: "btn btn-primary btn-block" %>
</div>
<% end %>